CMakeLists.txt, Makefile, src/chess/board.h, src/chess/fen.cc, src/engine/evaluation/evaluation.cc, src/engine/evaluation/evaluation.h, src/engine/evaluation/evaluation_terms.h, src/engine/search/history/bonus.h, src/engine/search/history/continuation_history.h, src/engine/search/history/correction_history.h, src/engine/search/history/history.h, src/engine/search/history/quiet_history.h, src/engine/search/move_picker.cc, src/engine/search/search.cc, src/tuner/tuner.cc, src/utils/list.h, src/utils/types.h
This patch adds the static eval correction history, as implemented in Stockfish.
When the static evaluation does not match the resulting search bound, the correction value for the current pawn structure gets adjusted to move future static evals closer to the actual search result.
STC:
```
Elo   | 11.82 +- 6.90 (95%)
LLR   | 3.03 (-2.94, 2.94) [0.00, 5.00]
Games | N: 5030 W: 1387 L: 1216 D: 2427
Penta | [122, 590, 965, 671, 167]
https://chess.aronpetkovski.com/test/641/
```
Bench: 1165913
=> Correction history indexed by pawn hash

src/engine/search/search.cc
```
Elo   | 7.80 +- 5.10 (95%)
LLR   | 2.96 (-2.94, 2.94) [0.00, 5.00]
Games | N: 7488 W: 1990 L: 1822 D: 3676
Penta | [144, 880, 1559, 986, 175]
https://chess.aronpetkovski.com/test/1449/
```
Bench: 3177312
=> QS Futility Pruning

src/engine/search/history/continuation_history.h, src/engine/search/history/history.h
```
Elo   | 2.41 +- 1.85 (95%)
LLR   | 2.96 (-2.94, 2.94) [0.00, 5.00]
Games | N: 53416 W: 13783 L: 13412 D: 26221
Penta | [977, 6404, 11645, 6635, 1047]
https://chess.aronpetkovski.com/test/1471/
```
=> Introduce 4-ply Continuation History

src/engine/search/search.cc
```
Elo   | 1.63 +- 3.41 (95%)
LLR   | 3.29 (-2.25, 2.89) [-5.00, 0.00]
Games | N: 15568 W: 4106 L: 4033 D: 7429
Penta | [281, 1878, 3397, 1943, 285]
https://chess.aronpetkovski.com/test/1741/
```
=> Fix bound determination for TT score replacing static eval

src/engine/search/search.cc
```
Elo   | 0.69 +- 2.97 (95%)
LLR   | 2.96 (-2.25, 2.89) [-5.00, 0.00]
Games | N: 19680 W: 5011 L: 4972 D: 9697
Penta | [311, 2391, 4416, 2392, 330]
https://chess.aronpetkovski.com/test/1893/
```
=> Fix static eval not being initialized in QS

src/engine/search/search.cc, src/engine/search/transpo.h
```
Elo   | 5.52 +- 3.98 (95%)
LLR   | 2.91 (-2.25, 2.89) [0.00, 5.00]
Games | N: 10316 W: 2636 L: 2472 D: 5208
Penta | [126, 1192, 2396, 1280, 164]
https://chess.aronpetkovski.com/test/1950/
```
=> TT node was in PV reduction

src/engine/search/history/correction_history.h, src/engine/search/search.cc
```
Elo   | 9.75 +- 5.86 (95%)
Games | N: 5416 W: 1506 L: 1354 D: 2556
Penta | [86, 622, 1184, 686, 130]
https://chess.aronpetkovski.com/test/1978/
```
=> Different correction history logic

src/engine/search/history/correction_history.h, src/engine/search/search.cc
```
Elo   | 3.04 +- 2.27 (95%)
LLR   | 2.93 (-2.25, 2.89) [0.00, 3.00]
Games | N: 34378 W: 9078 L: 8777 D: 16523
Penta | [607, 4013, 7611, 4388, 570]
https://chess.aronpetkovski.com/test/1990/
```
=> Always use corrected static eval

README.md, src/engine/search/search.cc, src/engine/search/transpo.cc, src/engine/search/transpo.h
```
Elo   | 14.22 +- 7.02 (95%)
Games | N: 3202 W: 887 L: 756 D: 1559
Penta | [32, 329, 773, 410, 57]
https://chess.aronpetkovski.com/test/2957/
```
=> Store static eval in TT

src/engine/search/constants.h
```
Elo   | 4.62 +- 3.48 (95%)
Games | N: 12706 W: 3297 L: 3128 D: 6281
Penta | [141, 1457, 2995, 1612, 148]
https://chess.aronpetkovski.com/test/3310/
```
=> More aggressive NMP

src/engine/search/history/history.h, src/engine/search/search.cc
```
Elo   | 13.31 +- 6.82 (95%)
Games | N: 3526 W: 985 L: 850 D: 1691
Penta | [41, 368, 837, 449, 68]
https://chess.aronpetkovski.com/test/3367/
```
=> Only NMP when static eval is above beta

src/engine/search/search.cc, src/engine/search/stack.h
```
Elo   | 3.25 +- 2.63 (95%)
Games | N: 22896 W: 5995 L: 5781 D: 11120
Penta | [249, 2754, 5280, 2864, 301]
https://chess.aronpetkovski.com/test/3381/
```
=> Use previous move history in RFP margin

src/engine/search/search.cc
```
Elo   | 6.55 +- 4.92 (95%)
LLR   | 2.92 (-2.25, 2.89) [-4.00, 0.00]
Games | N: 6790 W: 1849 L: 1721 D: 3220
Penta | [93, 764, 1557, 884, 97]
https://chess.aronpetkovski.com/test/3461/
```
=> Fix Capture History Penalty

src/engine/search/constants.h, src/engine/search/search.cc
```
Elo   | 4.74 +- 3.56 (95%)
Games | N: 12532 W: 3267 L: 3096 D: 6169
Penta | [148, 1441, 2949, 1548, 180]
https://chess.aronpetkovski.com/test/3464/
```
=> Capture History LMR Reductions

src/engine/search/constants.h, src/engine/search/search.cc
```
Elo   | 5.29 +- 3.86 (95%)
LLR   | 2.89 (-2.25, 2.89) [0.00, 5.00]
Games | N: 10710 W: 2789 L: 2626 D: 5295
Penta | [127, 1231, 2495, 1356, 146]
https://chess.aronpetkovski.com/test/3468/
```
=> Capture History Pruning

src/engine/search/search.cc
```
Elo   | 5.67 +- 4.02 (95%)
Games | N: 9748 W: 2548 L: 2389 D: 4811
Penta | [106, 1137, 2243, 1268, 120]
https://chess.aronpetkovski.com/test/3480/
```
=> Negative extensions in cutnodes

src/engine/search/constants.h, src/engine/search/search.cc
```
Elo   | 1.67 +- 1.35 (95%)
Games | N: 83984 W: 21158 L: 20755 D: 42071
Penta | [951, 9951, 19758, 10408, 924]
```
=> Use LMR depth in Futility Pruning

src/engine/search/constants.h, src/engine/search/search.cc, src/engine/search/search.h, src/engine/search/stack.h
```
Elo   | 3.24 +- 2.62 (95%)
Games | N: 23946 W: 6293 L: 6070 D: 11583
Penta | [334, 2793, 5508, 2992, 346]
https://chess.aronpetkovski.com/test/3551/
```
=> Lower singular extension depth limit

src/engine/search/constants.h, src/engine/search/history/correction_history.h, src/engine/search/search.cc, src/engine/search/search.h, src/engine/search/stack.h, src/engine/search/transpo.h, src/utils/types.h
```
Elo   | 1.82 +- 3.08 (95%)
LLR   | 2.91 (-2.25, 2.89) [-4.00, 0.00]
Games | N: 17378 W: 4630 L: 4539 D: 8209
Penta | [238, 2042, 4082, 2045, 282]
https://chess.aronpetkovski.com/test/3560/
```
=> Fixing TB accuracy & pruning guards

src/engine/search/search.cc
```
Elo   | 6.03 +- 4.11 (95%)
LLR   | 2.95 (-2.25, 2.89) [0.00, 5.00]
Games | N: 8706 W: 2286 L: 2135 D: 4285
Penta | [90, 956, 2098, 1131, 78]
https://chess.aronpetkovski.com/test/3974/
```
=> Use smoothened improving in RFP

src/engine/search/search.cc
```
Elo   | 5.89 +- 3.91 (95%)
Games | N: 7664 W: 1902 L: 1772 D: 3990
Penta | [16, 842, 1985, 974, 15]
https://chess.aronpetkovski.com/test/3996/
```
=> Use improving rate in LMR

src/engine/search/history/quiet_history.h, src/engine/search/search.cc, src/engine/search/stack.h
Unfinished SPRT, hoping that a tune will yield more elo from it.
```
Elo   | 1.46 +- 1.78 (95%)
LLR   | 1.29 (-2.25, 2.89) [0.00, 3.00]
Games | N: 41136 W: 10081 L: 9908 D: 21147
Penta | [189, 4886, 10268, 5013, 212]
https://chess.aronpetkovski.com/test/4048/
```
=> Update history score based on static eval difference

src/engine/search/search.cc
```
Elo   | 4.29 +- 3.24 (95%)
Games | N: 13116 W: 3265 L: 3103 D: 6748
Penta | [80, 1539, 3161, 1695, 83]
https://chess.aronpetkovski.com/test/4229/
```
=> Use improving heuristic in futility pruning

src/engine/search/search.cc, src/engine/search/stack.h
One of the saddest patches I've had to do in a while. I will experiment with getting dynamic improving to work again later on, but in the quest for Elo, it must go away for now.
STC
```
Elo   | 3.17 +- 2.54 (95%)
LLR   | 2.94 (-2.25, 2.89) [0.00, 5.00]
Games | N: 21790 W: 5761 L: 5562 D: 10467
Penta | [147, 2592, 5250, 2727, 179]
https://chess.aronpetkovski.com/test/4264/
```
LTC (unfinished)
```
Elo   | 13.25 +- 9.02 (95%)
LLR   | 1.46 (-2.25, 2.89) [0.00, 5.00]
Games | N: 1548 W: 419 L: 360 D: 769
Penta | [6, 158, 387, 217, 6]
https://chess.aronpetkovski.com/test/4279/
```
=> Simplify away dynamic improving (for now)

src/engine/evaluation/evaluation.cc
```
Elo   | 8.33 +- 4.93 (95%)
LLR   | 2.91 (-2.25, 2.89) [0.00, 5.00]
Games | N: 5296 W: 1415 L: 1288 D: 2593
Penta | [27, 568, 1329, 699, 25]
https://chess.aronpetkovski.com/test/4286/
```
=> Scale NNUE evaluation based on game phase

src/engine/search/search.cc
```
Elo   | 2.02 +- 1.60 (95%)
Games | N: 52500 W: 13600 L: 13295 D: 25605
Penta | [313, 6236, 12857, 6521, 323]
https://chess.aronpetkovski.com/test/4319/
```
=> Reduce more in cut nodes

src/engine/search/history/continuation_history.h, src/engine/search/search.cc
```
Elo   | 2.97 +- 2.14 (95%)
Games | N: 28758 W: 7200 L: 6954 D: 14604
Penta | [150, 3372, 7096, 3604, 157]
https://chess.aronpetkovski.com/test/4458/
```
=> Update Continuation History on LMR re-search

src/engine/search/search.cc
```
Elo   | 3.70 +- 3.68 (95%)
LLR   | 2.91 (-2.25, 2.89) [-4.00, 0.00]
Games | N: 9856 W: 2564 L: 2459 D: 4833
Penta | [46, 1159, 2436, 1218, 69]
https://chess.aronpetkovski.com/test/4472/
```
=> Simplify out check extensions

src/engine/search/search.cc
```
Elo   | 4.03 +- 2.61 (95%)
Games | N: 19384 W: 4973 L: 4748 D: 9663
Penta | [110, 2219, 4808, 2446, 109]
https://chess.aronpetkovski.com/test/4511/
```
=> Use Capture History in the MovePicker SEE threshold

src/engine/search/search.cc
```
Elo   | 2.18 +- 3.02 (95%)
LLR   | 2.92 (-2.25, 2.89) [-4.00, 0.00]
Games | N: 14490 W: 3678 L: 3587 D: 7225
Penta | [82, 1695, 3595, 1796, 77]
https://chess.aronpetkovski.com/test/4512/
```
=> Fix Continuation History LMR research bonus

src/chess/board.cc, src/chess/board.h, src/engine/search/move_picker.cc, src/engine/search/search.cc
```
Elo   | 2.52 +- 1.90 (95%)
Games | N: 35586 W: 8914 L: 8656 D: 18016
Penta | [143, 4218, 8849, 4404, 179]
https://chess.aronpetkovski.com/test/4628/
```
=> Use enemy threats for quiet move ordering

src/engine/search/constants.h, src/engine/search/search.cc
```
Elo   | 1.76 +- 1.43 (95%)
Games | N: 63796 W: 15992 L: 15668 D: 32136
Penta | [275, 7635, 15795, 7877, 316]
https://chess.aronpetkovski.com/test/4654/
```
Should scale well at LTC.
=> Triple extensions

src/engine/search/search.cc
```
Elo   | 1.61 +- 1.31 (95%)
Games | N: 76734 W: 19419 L: 19063 D: 38252
Penta | [380, 9177, 18972, 9383, 455]
https://chess.aronpetkovski.com/test/4638/
```
=> No LMR on capture moves in PV nodes

src/engine/search/search.cc
```
Elo   | 2.06 +- 1.63 (95%)
Games | N: 48484 W: 12138 L: 11850 D: 24496
Penta | [212, 5701, 12171, 5903, 255]
https://chess.aronpetkovski.com/test/4678/
```
=> Use corrected evaluation as a complexity metric in LMR

src/engine/evaluation/evaluation.cc
```
Elo   | 4.55 +- 4.06 (95%)
LLR   | 2.90 (-2.25, 2.89) [-4.00, 0.00]
Games | N: 8558 W: 2232 L: 2120 D: 4206
Penta | [48, 1017, 2077, 1049, 88]
https://chess.aronpetkovski.com/test/4799/
```
=> Simplify away evaluation material scaling

src/engine/search/search.cc
```
Elo   | 1.85 +- 1.50 (95%)
Games | N: 62492 W: 16166 L: 15833 D: 30493
Penta | [450, 7470, 15098, 7753, 475]
https://chess.aronpetkovski.com/test/4822/
```
=> Use move history score in futility pruning

src/engine/search/search.cc
Patch from Berserk.
```
Elo   | 1.10 +- 0.78 (95%)
Games | N: 231014 W: 59505 L: 58773 D: 112736
Penta | [1710, 27618, 56120, 28348, 1711]
https://chess.aronpetkovski.com/test/4938/
```
=> Stricter TT cutoff conditions in PVS

src/engine/search/history/correction_history.h, src/engine/search/search.cc, src/engine/search/stack.h
```
Elo   | -0.10 +- 3.37 (95%)
LLR   | 0.64 (-2.25, 2.89) [-4.00, 0.00]
Games | N: 10664 W: 2716 L: 2719 D: 5229
Penta | [59, 1160, 2898, 1155, 60]
https://chess.aronpetkovski.com/test/4996/
```
=> Fix scores being 0 when hard cutoff

src/engine/search/search.cc
```
Elo   | 4.90 +- 2.98 (95%)
Games | N: 15588 W: 4148 L: 3928 D: 7512
Penta | [92, 1827, 3762, 1995, 118]
https://chess.aronpetkovski.com/test/5223/
```
=> Store to TT during QS stand-pat cutoff

src/engine/search/search.cc
```
Elo   | 3.64 +- 2.45 (95%)
Games | N: 22076 W: 5813 L: 5582 D: 10681
Penta | [139, 2497, 5525, 2748, 129]
https://chess.aronpetkovski.com/test/5232/
```
=> Utilize improving heuristic in NMP

src/engine/search/search.cc
```
Elo   | 2.79 +- 2.04 (95%)
LLR   | 2.94 (-2.25, 2.89) [0.00, 3.00]
Games | N: 32046 W: 8323 L: 8066 D: 15657
Penta | [183, 3748, 7920, 3973, 199]
https://chess.aronpetkovski.com/test/5257/
```
=> Increase history bonus & penalty when `alpha > beta + 50`

src/engine/search/search.cc
```
Elo   | 1.98 +- 1.58 (95%)
Games | N: 52952 W: 13511 L: 13209 D: 26232
Penta | [293, 6246, 13102, 6536, 299]
https://chess.aronpetkovski.com/test/5282/
```
=> Tweak negative extensions

src/engine/search/search.cc
```
Elo   | 2.65 +- 1.98 (95%)
Games | N: 33260 W: 8468 L: 8214 D: 16578
Penta | [149, 3911, 8286, 4105, 179]
https://chess.aronpetkovski.com/test/5297/
```
=> Reduce killer moves less

src/engine/search/move_picker.cc
```
Elo   | 1.44 +- 1.56 (95%)
LLR   | 1.62 (-2.25, 2.89) [0.00, 3.00]
Games | N: 53340 W: 13490 L: 13269 D: 26581
Penta | [239, 6392, 13201, 6585, 253]
https://chess.aronpetkovski.com/test/5300/
```
=> Split captures using capture history in ProbCut

src/engine/search/constants.h, src/engine/search/search.cc
```
Elo   | 1.05 +- 0.86 (95%)
LLR   | 2.03 (-2.25, 2.89) [0.00, 3.00]
Games | N: 187340 W: 47938 L: 47370 D: 92032
Penta | [1249, 22453, 45700, 23017, 1251]
https://chess.aronpetkovski.com/test/5481/
```
=> Use quiet history for SEE pruning

src/engine/search/search.cc
```
Elo   | 2.64 +- 1.98 (95%)
Games | N: 33846 W: 8609 L: 8352 D: 16885
Penta | [159, 4023, 8344, 4196, 201]
https://chess.aronpetkovski.com/test/5599/
```
=> Use static evaluation for futility pruning

src/engine/search/search.cc
```
Elo   | 2.38 +- 1.82 (95%)
Games | N: 38068 W: 9184 L: 8923 D: 19961
Penta | [155, 4447, 9570, 4706, 156]
https://chess.aronpetkovski.com/test/5698/
```
=> Increase RFP margin lower limit

src/engine/search/search.cc
STC
```
Elo   | 2.56 +- 1.91 (95%)
LLR   | 2.94 (-2.25, 2.89) [0.00, 3.00]
Games | N: 35122 W: 8583 L: 8324 D: 18215
Penta | [163, 4095, 8763, 4400, 140]
https://chess.aronpetkovski.com/test/5708/
```
LTC
```
Elo   | 1.54 +- 1.52 (95%)
LLR   | 1.97 (-2.25, 2.89) [0.00, 3.00]
Games | N: 50608 W: 12224 L: 12000 D: 26384
Penta | [86, 5911, 13071, 6165, 71]
https://chess.aronpetkovski.com/test/5713/
```
=> Increase SE depth reduction

src/engine/search/history/continuation_history.h, src/engine/search/time_mgmt.cc
```
Elo   | 2.61 +- 1.98 (95%)
Games | N: 36032 W: 9322 L: 9051 D: 17659
Penta | [264, 4268, 8701, 4499, 284]
https://chess.aronpetkovski.com/test/5740/
```
=> 6-ply continuation history

src/engine/evaluation/evaluation.cc
Re-introduced into Integral using Stormphrax formula
```
Elo   | 3.77 +- 2.49 (95%)
Games | N: 20660 W: 5185 L: 4961 D: 10514
Penta | [113, 2342, 5156, 2646, 73]
https://chess.aronpetkovski.com/test/5758/
```
=> Scale evaluation based on material

src/engine/search/history/bonus.h, src/engine/search/history/capture_history.h, src/engine/search/history/continuation_history.h, src/engine/search/history/quiet_history.h
```
Elo   | 4.53 +- 5.44 (95%)
SPRT  | 4.0+0.04s Threads=1 Hash=16MB
LLR   | 0.79 (-2.25, 2.89) [0.00, 3.00]
Games | N: 4682 W: 1212 L: 1151 D: 2319
Penta | [36, 516, 1185, 559, 45]
https://chess.aronpetkovski.com/test/5766/
```
=> Switch to using I16's for histories

src/engine/search/search.cc
```
Elo   | 2.80 +- 2.06 (95%)
Games | N: 31240 W: 7815 L: 7563 D: 15862
Penta | [155, 3676, 7731, 3878, 180]
https://chess.aronpetkovski.com/test/5793/
```
=> RFP less often when opponent has a guaranteed winning capture

src/engine/search/search.cc
```
Elo   | 1.76 +- 1.42 (95%)
LLR   | 2.93 (-2.25, 2.89) [0.00, 3.00]
Games | N: 65792 W: 16356 L: 16022 D: 33414
Penta | [366, 7828, 16158, 8194, 350]
https://chess.aronpetkovski.com/test/5786/
```
=> TT cutoff depth tweak

src/engine/search/search.cc
```
Elo   | 1.11 +- 1.08 (95%)
LLR   | 1.65 (-2.25, 2.89) [0.00, 3.00]
Games | N: 113190 W: 28058 L: 27695 D: 57437
Penta | [612, 13463, 28142, 13706, 672]
https://chess.aronpetkovski.com/test/5828/
```
=> Fail-soft multicut

src/engine/search/search.cc
Idea from SF
```
Elo   | 2.71 +- 2.00 (95%)
Games | N: 32188 W: 8061 L: 7810 D: 16317
Penta | [146, 3775, 8005, 4018, 150]
https://chess.aronpetkovski.com/test/5914/
```
=> Reduce after fail-lows in mid-depth search

src/engine/search/search.cc
Idea from SF
```
Elo   | 2.71 +- 2.00 (95%)
Games | N: 32188 W: 8061 L: 7810 D: 16317
Penta | [146, 3775, 8005, 4018, 150]
https://chess.aronpetkovski.com/test/5914/
```
=> Reduce if an alpha raise didn't cause a cutoff

src/engine/search/search.cc
Good enough
```
Elo   | 0.96 +- 4.70 (95%)
LLR   | 0.73 (-2.25, 2.89) [-4.00, 0.00]
Games | N: 5810 W: 1439 L: 1423 D: 2948
Penta | [29, 683, 1463, 703, 27]
https://chess.aronpetkovski.com/test/5961/
```
=> Fix not setting history score in ProbCut

src/engine/search/search.cc
STC
```
Elo   | 2.09 +- 1.66 (95%)
Games | N: 47614 W: 11754 L: 11467 D: 24393
Penta | [215, 5690, 11727, 5943, 232]
https://chess.aronpetkovski.com/test/6030/
```
LTC
```
Elo   | 3.16 +- 2.17 (95%)
Games | N: 23414 W: 5383 L: 5170 D: 12861
Penta | [15, 2617, 6235, 2820, 20]
https://chess.aronpetkovski.com/test/6045/
```
=> Tweak RFP margin depending on opponent's evaluation trend

src/engine/search/search.cc
```
Elo   | 4.35 +- 2.67 (95%)
LLR   | 2.99 (-2.25, 2.89) [0.00, 3.00]
Games | N: 17484 W: 4301 L: 4082 D: 9101
Penta | [55, 2018, 4388, 2215, 66]
https://chess.aronpetkovski.com/test/6106/
```
=> Allow LMR to increase depth in all-nodes

src/engine/search/search.cc
```
Elo   | 0.57 +- 2.07 (95%)
LLR   | 2.90 (-2.25, 2.89) [-4.00, 0.00]
Games | N: 28056 W: 6825 L: 6779 D: 14452
Penta | [114, 3181, 7373, 3265, 95]
https://chess.aronpetkovski.com/test/6147/
```
=> Fix positive SEE threshold being applied for quiet moves

src/engine/search/history/correction_history.h
```
Elo   | 3.80 +- 2.52 (95%)
Games | N: 20546 W: 5087 L: 4862 D: 10597
Penta | [97, 2390, 5082, 2599, 105]
https://chess.aronpetkovski.com/test/6231/
```
=> Tweak non-pawn correction history

src/engine/evaluation/nnue/accumulator.h, src/engine/search/search.cc, src/engine/search/search.h, src/engine/search/time_mgmt.cc, src/engine/search/time_mgmt.h
Should mainly help with puzzle solving, although it may also be a gainer at higher depths.
```
Elo   | 0.38 +- 1.95 (95%)
LLR   | 2.91 (-2.25, 2.89) [-4.00, 0.00]
Games | N: 32088 W: 7828 L: 7793 D: 16467
Penta | [115, 3748, 8295, 3759, 127]
https://chess.aronpetkovski.com/test/6242/
```
=> Verify NMP cutoff scores at high-depths

src/engine/search/history/bonus.h
```
Elo   | 5.24 +- 3.06 (95%)
Games | N: 14116 W: 3539 L: 3326 D: 7251
Penta | [66, 1645, 3423, 1858, 66]
https://chess.aronpetkovski.com/test/6246/
```
=> Add a static bias to history bonuses

src/engine/search/history/correction_history.h
```
Elo   | 1.36 +- 2.60 (95%)
LLR   | 2.90 (-2.25, 2.89) [-4.00, 0.00]
Games | N: 19098 W: 4710 L: 4635 D: 9753
Penta | [89, 2275, 4741, 2360, 84]
https://chess.aronpetkovski.com/test/6247/
```
=> Simplify away minor-piece correction history

src/engine/search/history/capture_history.h
```
Elo   | 1.97 +- 1.56 (95%)
Games | N: 52114 W: 12633 L: 12338 D: 27143
Penta | [196, 6216, 12955, 6477, 213]
https://chess.aronpetkovski.com/test/6340/
```
=> Tweak capture history table structure

src/engine/search/search.h, src/engine/search/time_mgmt.cc, src/engine/search/transpo.cc
```
Elo   | 1.19 +- 0.93 (95%)
Games | N: 143278 W: 35138 L: 34646 D: 73494
Penta | [546, 16616, 36856, 17042, 579]
https://chess.aronpetkovski.com/test/6382/
```
=> Only age TT entries when storing to them

src/engine/evaluation/evaluation.h, src/engine/search/constants.h, src/engine/search/history/bonus.h, src/engine/search/history/correction_history.h, src/engine/search/move_picker.cc, src/engine/search/search.cc, src/engine/search/time_mgmt.cc, src/tuner/spsa.h
Did better at STC than LTC somehow?
STC
```
Elo   | 8.43 +- 3.99 (95%)
Games | N: 8034 W: 2068 L: 1873 D: 4093
Penta | [28, 890, 1998, 1061, 40]
https://chess.aronpetkovski.com/test/6484/
```
LTC
```
Elo   | 3.30 +- 2.24 (95%)
Games | N: 22298 W: 5214 L: 5002 D: 12082
Penta | [16, 2519, 5868, 2729, 17]
https://chess.aronpetkovski.com/test/6487/
```
=> LTC SPSA Tune

src/engine/search/constants.h
Unfinished SPRT, but in the words of Gabe (Obsidian author): it scales, trust.
```
Elo   | 1.31 +- 1.62 (95%)
LLR   | 1.22 (-2.25, 2.89) [0.00, 3.00]
Games | N: 47836 W: 11575 L: 11394 D: 24867
Penta | [158, 5733, 11998, 5828, 201]
https://chess.aronpetkovski.com/test/6537/
```
=> RFP more often

src/engine/search/history/correction_history.h
```
Elo   | 6.31 +- 3.36 (95%)
LLR   | 2.95 (-2.25, 2.89) [0.00, 3.00]
Games | N: 11294 W: 2795 L: 2590 D: 5909
Penta | [30, 1317, 2765, 1488, 47]
https://chess.aronpetkovski.com/test/6549/
```
=> Switch to history gravity formula for correction history

src/engine/search/search.cc
STC
```
Elo   | 1.44 +- 1.17 (95%)
Games | N: 92788 W: 22492 L: 22107 D: 48189
Penta | [342, 11071, 23229, 11364, 388]
https://chess.aronpetkovski.com/test/6554/
```
Unfinished LTC
```
Elo   | 2.80 +- 4.19 (95%)
LLR   | 0.67 (-2.25, 2.89) [0.00, 3.00]
Games | N: 6586 W: 1554 L: 1501 D: 3531
Penta | [4, 771, 1697, 810, 11]
https://chess.aronpetkovski.com/test/6565/
```
=> Update capture history in quiescent search

src/engine/search/search.cc
Test was actually playing at twice the TC listed due to reference NPS mismatch.
```
Elo   | 2.39 +- 2.30 (95%)
LLR   | 1.80 (-2.25, 2.89) [0.00, 3.00]
Games | N: 22434 W: 5390 L: 5236 D: 11808
Penta | [46, 2584, 5819, 2706, 62]
https://chess.aronpetkovski.com/test/6984/
```
=> More futility pruning in non-PV nodes

src/engine/search/search.cc
```
Elo   | 2.39 +- 1.83 (95%)
Games | N: 38138 W: 9308 L: 9046 D: 19784
Penta | [138, 4538, 9479, 4752, 162]
https://chess.aronpetkovski.com/test/7014/
```
=> Update last move's pawn history based on static eval difference

CMakeLists.txt, src/engine/search/constants.h, src/engine/search/search.cc
Speculative LTC passed, STC looked neutral.
```
Elo   | 2.88 +- 2.04 (95%)
Games | N: 27058 W: 6411 L: 6187 D: 14460
Penta | [17, 3094, 7096, 3292, 30]
https://chess.aronpetkovski.com/test/7097/
```
=> Tweak negative extensions and singular extension minimum depth

src/chess/move.cc, src/engine/search/search.cc
Passed STC:
```Elo   | 1.93 +- 1.55 (95%)
Games | N: 53894 W: 13237 L: 12937 D: 27720
Penta | [239, 6405, 13373, 6677, 253]
```
https://chess.aronpetkovski.com/test/7087/
Passed LTC:
```
Elo   | 2.00 +- 2.59 (95%)
LLR   | 1.06 (-2.25, 2.89) [0.00, 3.00]
Games | N: 16368 W: 3841 L: 3747 D: 8780
Penta | [11, 1852, 4355, 1964, 2]
```
https://chess.aronpetkovski.com/test/7111/
=> Bonus to Prior Countermoves on Fail Low

src/engine/search/history/pawn_history.h
```
Elo   | 3.64 +- 3.55 (95%)
LLR   | 2.96 (-2.25, 2.89) [-4.00, 0.00]
Games | N: 9916 W: 2413 L: 2309 D: 5194
Penta | [33, 1143, 2511, 1229, 42]
https://chess.aronpetkovski.com/test/7222/
```
=> Fix pawn history population

src/engine/search/search.cc, src/engine/search/search.h
STC:
```
Elo   | 4.80 +- 2.90 (95%)
Games | N: 15270 W: 3741 L: 3530 D: 7999
Penta | [66, 1729, 3844, 1920, 76]
```
https://chess.aronpetkovski.com/test/7338/
LTC:
```
Elo   | 3.09 +- 3.20 (95%)
LLR   | 1.31 (-2.25, 2.89) [0.00, 3.00]
Games | N: 11004 W: 2607 L: 2509 D: 5888
Penta | [7, 1256, 2881, 1348, 10]
```
https://chess.aronpetkovski.com/test/7344/
bench 2276556
=> Tweak aspiration window with squared average score of the best move

src/engine/search/search.cc
```
Elo   | -0.50 +- 2.51 (95%)
LLR   | -1.22 (-2.25, 2.89) [0.00, 3.00]
Games | N: 19956 W: 4728 L: 4757 D: 10471
Penta | [86, 2392, 5039, 2387, 74]
```
<https://chess.aronpetkovski.com/test/7501/>
This would pass simplification, and probably scales at LTC.
=> Remove depth limit from SEE pruning

src/engine/search/search.cc
Would have passed simplification bounds a long time ago
```
Elo   | 0.73 +- 1.06 (95%)
LLR   | -0.28 (-2.25, 2.89) [0.00, 3.00]
Games | N: 112106 W: 27088 L: 26852 D: 58166
Penta | [523, 13110, 28562, 13324, 534]
```
<https://chess.aronpetkovski.com/test/7602/>
=> Simplify `in_pv_node` condition in negative extensions

src/engine/evaluation/nnue/nnue.cc, src/engine/search/search.cc
```
Elo   | 5.90 +- 4.21 (95%)
SPRT  | 4.0+0.04s Threads=1 Hash=16MB
LLR   | 2.90 (-2.25, 2.89) [-3.00, 1.00]
Games | N: 7132 W: 1848 L: 1727 D: 3557
Penta | [43, 730, 1911, 827, 55]
```
<https://chess.aronpetkovski.com/test/7622/>
=> Sparsity table speedup

src/engine/search/transpo.cc
```
Elo   | 1.84 +- 1.47 (95%)
Games | N: 58042 W: 14061 L: 13754 D: 30227
Penta | [231, 6779, 14739, 6996, 276]
```
<https://chess.aronpetkovski.com/test/8380/>
```
Elo   | 7.08 +- 3.50 (95%)
Games | N: 8830 W: 2122 L: 1942 D: 4766
Penta | [8, 904, 2414, 1078, 11]
```
<https://chess.aronpetkovski.com/test/8383/>
=> Always replace TT entries from past searches

src/engine/search/constants.h, src/engine/search/search.cc
```
Elo   | 1.22 +- 0.99 (95%)
LLR   | 2.89 (-2.25, 2.89) [0.00, 2.50]
Games | N: 130318 W: 31374 L: 30916 D: 68028
Penta | [522, 15613, 32513, 15907, 604]
```
<https://chess.aronpetkovski.com/test/8411/>
=> Return interpolated score during QS beta cutoff

src/engine/search/search.cc
```
Elo   | 1.42 +- 1.15 (95%)
Games | N: 99794 W: 24938 L: 24531 D: 50325
Penta | [568, 11801, 24731, 12250, 547]
```
<https://chess.aronpetkovski.com/test/8863/>
=> Increase assumed fail high negative extension amount

src/chess/board.cc, src/chess/board.h, src/chess/move_gen.cc, src/engine/evaluation/evaluation.cc
Idea from Pawnocchio
STC
```
Elo   | 2.17 +- 1.63 (95%)
Games | N: 49730 W: 12367 L: 12056 D: 25307
Penta | [256, 5873, 12358, 6060, 318]
```
<https://chess.aronpetkovski.com/test/9001/>
LTC
```
Elo   | 2.07 +- 2.24 (95%)
LLR   | 1.37 (-2.25, 2.89) [0.00, 2.50]
Games | N: 22300 W: 5326 L: 5193 D: 11781
Penta | [21, 2531, 5922, 2646, 30]
```
<https://chess.aronpetkovski.com/test/9007/>
=> Restrict pinned pieces in SEE

src/engine/search/search.cc
Honestly cannot see how this isn't elo-gaining, so the test wasn't completed.
```
Elo   | 1.04 +- 1.03 (95%)
LLR   | 1.78 (-2.25, 2.89) [0.00, 2.50]
Games | N: 125022 W: 30834 L: 30461 D: 63727
Penta | [645, 15053, 30781, 15348, 684]
```
<https://chess.aronpetkovski.com/test/9081/>
=> Use corrected evaluation as a SEE threshold modifier in ProbCut

src/engine/search/history/history.h
Would have passed simplification.
```
Elo   | 0.64 +- 1.39 (95%)
LLR   | -0.01 (-2.25, 2.89) [0.00, 2.50]
Games | N: 63464 W: 15326 L: 15209 D: 32929
Penta | [200, 7585, 16049, 7694, 204]
```
https://furybench.com/test/191/
=> Simplify pawn history usage

src/engine/search/search.cc, src/engine/search/stack.h
STC
```
Elo   | 2.38 +- 1.73 (95%)
LLR   | 2.89 (-2.25, 2.89) [0.00, 2.50]
Games | N: 41686 W: 10217 L: 9931 D: 21538
Penta | [121, 4928, 10501, 5130, 163]
```
https://furybench.com/test/366/
```
Elo   | 4.87 +- 4.68 (95%)
LLR   | 0.93 (-2.25, 2.89) [0.00, 2.50]
Games | N: 5284 W: 1272 L: 1198 D: 2814
Penta | [8, 591, 1369, 667, 7]
```
https://furybench.com/test/369/
=> Use static evaluation correction difference in RFP

src/engine/search/constants.h, src/engine/search/search.cc
STC
```
Elo   | 2.60 +- 1.83 (95%)
LLR   | 2.91 (-2.25, 2.89) [0.00, 2.50]
Games | N: 37530 W: 9258 L: 8977 D: 19295
Penta | [125, 4415, 9433, 4638, 154]
```
https://furybench.com/test/494/
LTC
```
Elo   | 1.17 +- 1.20 (95%)
LLR   | 1.80 (-2.25, 2.89) [0.00, 2.50]
Games | N: 76704 W: 18216 L: 17958 D: 40530
Penta | [77, 8763, 20419, 9011, 82]
```
https://furybench.com/test/518/
=> Interpolate fail-high scores in QS

src/engine/search/search.cc
STC
```
Elo   | 3.13 +- 2.06 (95%)
Games | N: 29168 W: 7117 L: 6854 D: 15197
Penta | [93, 3394, 7355, 3641, 101]
```
https://furybench.com/test/1025/
LTC
```
Elo   | 2.07 +- 2.25 (95%)
LLR   | 1.37 (-2.25, 2.89) [0.00, 2.50]
Games | N: 22460 W: 5319 L: 5185 D: 11956
Penta | [21, 2595, 5864, 2729, 21]
```
https://furybench.com/test/1032/
=> LMP more often when static eval suggests a fail high

src/engine/search/search.cc
```
Elo   | 1.20 +- 0.98 (95%)
LLR   | 2.89 (-2.25, 2.89) [0.00, 2.50]
Games | N: 129344 W: 31218 L: 30770 D: 67356
Penta | [424, 15327, 32733, 15753, 435]
```
https://furybench.com/test/1134/
=> Add recapture guard to QS futility pruning

src/chess/board.cc
Nice elo.
```
Elo   | 0.69 +- 1.71 (95%)
LLR   | 2.91 (-2.25, 2.89) [-3.00, 1.00]
Games | N: 35970 W: 8651 L: 8580 D: 18739
Penta | [105, 3646, 10404, 3733, 97]
```
https://furybench.com/test/1181/
=> Simplify insufficient material check from search

src/engine/search/search.cc
STC
```
Elo   | 2.31 +- 2.74 (95%)
LLR   | 2.98 (-2.25, 2.89) [-3.00, 1.00]
Games | N: 16406 W: 3975 L: 3866 D: 8565
Penta | [51, 1916, 4161, 2023, 52]
```
https://furybench.com/test/1417/
LTC
```
Elo   | 0.19 +- 1.33 (95%)
LLR   | 2.91 (-2.25, 2.89) [-3.00, 1.00]
Games | N: 62864 W: 14733 L: 14698 D: 33433
Penta | [50, 7254, 16810, 7247, 71]
```
https://furybench.com/test/1424/
=> Return alpha when no legal moves exist in singular search

src/engine/search/search.cc
```
Elo   | 7.57 +- 3.81 (95%)
LLR   | 3.52 (-2.25, 2.89) [0.00, 4.00]
Games | N: 8222 W: 2092 L: 1913 D: 4217
Penta | [18, 883, 2143, 1036, 31]
```
https://furybench.com/test/1556/
LTC
```
Elo   | 2.04 +- 1.66 (95%)
LLR   | 2.89 (-2.25, 2.89) [0.00, 4.00]
Games | N: 39954 W: 9850 L: 9615 D: 20489
Penta | [23, 4551, 10599, 4776, 28]
```
https://furybench.com/test/1559/
=> Interpolate between fail-hard and fail-soft based on depth

src/engine/search/search.cc
```
Elo   | 1.17 +- 2.12 (95%)
LLR   | 2.95 (-2.25, 2.89) [-3.00, 1.00]
Games | N: 27086 W: 6790 L: 6699 D: 13597
Penta | [70, 3208, 6904, 3283, 78]
```
https://furybench.com/test/1688/
=> Fix capture history malus
