src/engine/evaluation/evaluation.cc
src/engine/evaluation/terms.h
src/engine/search/search.cc
src/tuner/tuner.cc
src/tuner/tuner.h

```cpp
Elo   | 26.41 +- 10.04 (95%)
LLR   | 2.99 (-2.94, 2.94) [0.00, 5.00]
Games | N: 1898 W: 591 L: 447 D: 860
Penta | [34, 165, 430, 263, 57]
https://chess.aronpetkovski.com/test/1452/
```
Bench: 3725456

Defended pawns

---

src/chess/move_gen.cc
src/chess/move_gen.h
src/engine/evaluation/evaluation.cc
src/engine/evaluation/terms.h
src/engine/search/search.cc
src/tuner/tuner.cc
src/tuner/tuner.h

```
Elo   | 28.72 +- 10.61 (95%)
LLR   | 2.99 (-2.94, 2.94) [0.00, 5.00]
Games | N: 1734 W: 528 L: 385 D: 821
Penta | [22, 174, 368, 245, 58]
https://chess.aronpetkovski.com/test/1458/
```

Safe checks

---

src/engine/evaluation/evaluation.h
src/engine/search/constants.h
src/engine/search/history/bonus.h
src/engine/search/history/correction_history.h
src/engine/search/search.cc
src/engine/search/search.h
src/engine/search/time_mgmt.cc
src/utils/types.h

Tuned for 6250 iterations (50002 games played)
LTC SPRT:
```
Elo   | 11.28 +- 6.09 (95%)
SPRT  | 40.0+0.40s Threads=1 Hash=16MB
Games | N: 4036 W: 1033 L: 902 D: 2101
Penta | [40, 410, 1005, 505, 58]
https://chess.aronpetkovski.com/test/1714/
```
STC SPRT:
```
Elo   | 17.36 +- 8.08 (95%)
Games | N: 2824 W: 803 L: 662 D: 1359
Penta | [40, 309, 598, 400, 65]
https://chess.aronpetkovski.com/test/1715/
```

LTC SPSA Tune

---

src/engine/search/constants.h
src/engine/search/history/correction_history.h
src/engine/search/search.cc
src/engine/search/stack.h

```
Elo   | 10.95 +- 6.14 (95%)
LLR   | 2.94 (-2.25, 2.89) [0.00, 5.00]
Games | N: 4666 W: 1242 L: 1095 D: 2329
Penta | [69, 526, 1006, 653, 79]
https://chess.aronpetkovski.com/test/1807/
```

Add improving heuristic to RFP

---

src/engine/evaluation/evaluation.cc
src/engine/evaluation/terms.h

```
Elo   | 7.90 +- 4.98 (95%)
LLR   | 2.99 (-2.25, 2.89) [0.00, 5.00]
Games | N: 6862 W: 1843 L: 1687 D: 3332
Penta | [88, 800, 1530, 894, 119]
https://chess.aronpetkovski.com/test/1865/
```

Piece X-Ray Mobility

---

src/engine/evaluation/evaluation.cc
src/engine/evaluation/terms.h
src/tuner/tuner.cc
src/tuner/tuner.h

```
Elo   | 13.72 +- 6.90 (95%)
LLR   | 2.94 (-2.25, 2.89) [0.00, 5.00]
Games | N: 3522 W: 1000 L: 861 D: 1661
Penta | [52, 351, 827, 468, 63]
https://chess.aronpetkovski.com/test/2023/
```

Defended piece threats

---

src/chess/move_gen.cc
src/engine/evaluation/evaluation.cc
src/engine/evaluation/terms.h
src/tuner/tuner.cc
src/tuner/tuner.h

```
Elo   | 9.08 +- 5.51 (95%)
Games | N: 5700 W: 1534 L: 1385 D: 2781
Penta | [79, 652, 1262, 755, 102]
https://chess.aronpetkovski.com/test/2027/
```

Pawn push potential threats

---

src/engine/search/search.cc
src/engine/search/search.h
src/engine/uci/uci.cc
src/tests/bench_test.cc
src/tests/tests.h

Setup the foundation for thread pooling in Integral later on.
No bench change.

Thread pool foundation

---

src/engine/search/search.cc

```
Elo   | 16.71 +- 8.57 (95%)
LLR   | 2.90 (-2.25, 2.89) [-5.00, 0.00]
Games | N: 2352 W: 674 L: 561 D: 1117
Penta | [29, 245, 538, 312, 52]
https://chess.aronpetkovski.com/test/2186/
```

Fixed history pruning bug

---

src/engine/search/search.cc
src/engine/search/search.h
src/tests/bench_test.cc
src/utils/barrier.h

This should have been here a long time ago. Sorry.

Remove spin locking when idle

---

CMakeLists.txt
src/engine/search/search.cc
src/engine/search/transpo.h

```
Elo   | 2.86 +- 2.33 (95%)
Games | N: 25130 W: 6380 L: 6173 D: 12577
Penta | [144, 2981, 6134, 3136, 170]
https://chess.aronpetkovski.com/test/3925/
```

Use improving heuristic in razoring

---

src/engine/search/search.cc

```
Elo   | 7.03 +- 4.49 (95%)
LLR   | 2.95 (-2.25, 2.89) [0.00, 5.00]
Games | N: 6924 W: 1786 L: 1646 D: 3492
Penta | [47, 776, 1685, 898, 56]
https://chess.aronpetkovski.com/test/3936/
```

Change improving heuristic in RFP

---

CMakeLists.txt
src/engine/evaluation/nnue/accumulator.h
src/engine/search/constants.h
src/engine/search/history/quiet_history.h
src/engine/search/search.cc
src/engine/search/stack.h

```
Elo   | 3.94 +- 3.02 (95%)
Games | N: 14286 W: 3590 L: 3428 D: 7268
Penta | [65, 1673, 3500, 1845, 60]
https://chess.aronpetkovski.com/test/4089/
```

Tweak singular extensions

---

src/engine/evaluation/evaluation.cc

Tuning will solve any elo loss this brings later on.

Change material scaling formula

---

src/chess/board.h
src/engine/search/history/correction_history.h

```
Elo   | 5.66 +- 3.93 (95%)
LLR   | 2.91 (-2.25, 2.89) [0.00, 5.00]
Games | N: 8894 W: 2356 L: 2211 D: 4327
Penta | [56, 1017, 2159, 1156, 59]
https://chess.aronpetkovski.com/test/4311/
```

Minor & major piece indexed Correction History

---

src/engine/search/search.cc
src/engine/uci/reporter.h
src/engine/uci/uci.cc

Search info printing is now pretty (when `uci` has not been sent), with my favorite color: teal!

Pretty printing!

---

src/chess/board.cc
src/chess/board.h
src/engine/evaluation/nnue/accumulator.h
src/engine/uci/uci.cc

```
Elo   | 7.78 +- 3.78 (95%)
Games | N: 8536 W: 2223 L: 2032 D: 4281
Penta | [34, 872, 2285, 1023, 54]
https://chess.aronpetkovski.com/test/4471/
```

Cache each bucket's last known accumulator (finny tables)

---

src/engine/search/move_picker.cc
src/engine/search/search.cc

Accidentally merged the wrong branch.
```
Elo   | 4.69 +- 2.87 (95%)
Games | N: 15856 W: 4060 L: 3846 D: 7950
Penta | [70, 1833, 3920, 2023, 82]
https://chess.aronpetkovski.com/test/4507/
```

Capture History SEE (fixed)

---

src/engine/search/history/correction_history.h
src/engine/search/search.cc
src/engine/search/stack.h

```
Elo   | 1.25 +- 0.96 (95%)
LLR   | 2.94 (-2.25, 2.89) [0.00, 3.00]
Games | N: 149422 W: 38375 L: 37836 D: 73211
Penta | [1010, 18017, 36147, 18498, 1039]
https://chess.aronpetkovski.com/test/4977/
```

Continuation Correction History

---

src/engine/search/search.cc
src/engine/search/search.h
src/engine/search/time_mgmt.cc
src/engine/search/time_mgmt.h

Entirely taken from Berserk/SF. It's one of the things I don't have the confidence to do myself.
```
Elo   | 16.65 +- 5.78 (95%)
Games | N: 4030 W: 1144 L: 951 D: 1935
Penta | [28, 385, 993, 584, 25]
https://chess.aronpetkovski.com/test/5179/
```

Different time management

---

CMakeLists.txt
src/engine/search/search.cc

```
Elo   | 6.24 +- 3.40 (95%)
LLR   | 2.93 (-2.25, 2.89) [0.00, 3.00]
Games | N: 11808 W: 3089 L: 2877 D: 5842
Penta | [69, 1351, 2858, 1551, 75]
https://chess.aronpetkovski.com/test/5275/
```

Return a more balanced score in RFP

---

CMakeLists.txt
src/chess/board.cc
src/chess/board.h
src/data_gen/data_gen.h
src/engine/evaluation/nnue/nnue.cc
src/engine/evaluation/nnue/nnue.h
src/engine/search/cuckoo.cc
src/engine/search/cuckoo.h
src/engine/search/search.cc
src/main.cc
third-party/fathom/tbprobe.c
third-party/incbin/incbin.h

```
Elo   | 7.28 +- 3.73 (95%)
Games | N: 9736 W: 2588 L: 2384 D: 4764
Penta | [57, 1097, 2352, 1309, 53]
https://chess.aronpetkovski.com/test/5466/
```

Use cuckoo tables to detect upcoming repetitions

---

src/chess/board.cc
src/engine/search/search.cc
src/engine/search/time_mgmt.cc
src/engine/search/transpo.cc
src/engine/search/transpo.h

```
Elo   | 13.96 +- 5.34 (95%)
Games | N: 4954 W: 1347 L: 1148 D: 2459
Penta | [33, 522, 1174, 709, 39]
https://chess.aronpetkovski.com/test/5631/
```

Tweak TT quality formula and replacement policy

---

src/engine/search/search.cc
src/engine/search/time_mgmt.h

Don't evaluate in check in QS

---

src/engine/search/search.cc

```
Elo   | 0.32 +- 2.01 (95%)
LLR   | 2.90 (-2.25, 2.89) [-4.00, 0.00]
Games | N: 33742 W: 8582 L: 8551 D: 16609
Penta | [213, 4054, 8321, 4055, 228]
https://chess.aronpetkovski.com/test/5604/
```

Minor TT probing fix

---

src/engine/evaluation/nnue/accumulator.h
src/utils/simd.h

```
Elo   | 2.42 +- 1.83 (95%)
Games | N: 36352 W: 9143 L: 8890 D: 18319
Penta | [159, 3965, 9697, 4174, 181]
https://chess.aronpetkovski.com/test/5942/
```

Use SIMD for the accumulator

---

src/engine/search/search.cc

```
Elo   | 2.22 +- 1.73 (95%)
LLR   | 2.93 (-2.25, 2.89) [0.00, 3.00]
Games | N: 44450 W: 11023 L: 10739 D: 22688
Penta | [204, 5338, 10902, 5532, 249]
https://chess.aronpetkovski.com/test/5964/
```

Perform IIR if `tt_entry->depth + 4 < depth`

---

src/engine/search/search.cc

Tweak post-lmr conthist updates

---

src/engine/search/history/history.h
src/engine/search/history/pawn_history.h
src/engine/search/search.cc

```
Elo   | 1.38 +- 1.11 (95%)
LLR   | 2.95 (-2.25, 2.89) [0.00, 3.00]
Games | N: 102610 W: 24946 L: 24538 D: 53126
Penta | [364, 12234, 25697, 12650, 360]
https://chess.aronpetkovski.com/test/6660/
```

Pawn-Indexed Quiet History

---

src/engine/search/search.cc
src/engine/search/time_mgmt.cc

```
Elo   | 3.31 +- 3.37 (95%)
SPRT  | 4.0+0.04s Threads=1 Hash=16MB
LLR   | 3.00 (-2.25, 2.89) [-4.00, 0.00]
Games | N: 10714 W: 2738 L: 2636 D: 5340
Penta | [57, 1119, 2907, 1213, 61]
https://chess.aronpetkovski.com/test/6670/
```

Time loss fixes

---

src/engine/search/search.cc
src/engine/search/stack.h
src/engine/search/transpo.cc
src/engine/search/transpo.h
src/engine/uci/uci.h

Fix returning incorrect mate scores

---

src/engine/evaluation/nnue/accumulator.h
src/engine/search/history/pawn_history.h
src/utils/multi_array.h

Use SF-style Multiarray

---

CMakeLists.txt
src/engine/uci/uci.h

```
Elo   | 4.42 +- 2.78 (95%)
Games | N: 17234 W: 4407 L: 4188 D: 8639
Penta | [96, 1967, 4279, 2172, 103]
```
<https://chess.aronpetkovski.com/test/7569/>

New network

---

CMakeLists.txt
src/engine/search/history/continuation_entries.h
src/engine/search/history/continuation_history.h
src/engine/search/history/correction_history.h
src/engine/search/search.cc
src/engine/search/stack.h
src/engine/uci/uci.h

```
Elo   | 1.28 +- 1.02 (95%)
Games | N: 125310 W: 30232 L: 29769 D: 65309
Penta | [561, 14993, 31105, 15414, 582]
```
<https://chess.aronpetkovski.com/test/7578/>

3-ply Continuation Correction History

---

CMakeLists.txt
src/engine/evaluation/evaluation.cc
src/engine/evaluation/evaluation.h
src/engine/search/constants.h
src/engine/search/history/bonus.h
src/engine/search/history/correction_history.h
src/engine/search/history/pawn_history.h
src/engine/search/move_picker.cc
src/engine/search/search.cc
src/engine/search/time_mgmt.cc
src/tuner/spsa.h

```
Elo   | 4.42 +- 3.55 (95%)
SPRT  | 60.0+0.60s Threads=1 Hash=32MB
LLR   | 1.41 (-2.25, 2.89) [0.00, 2.50]
Games | N: 8564 W: 2011 L: 1902 D: 4651
Penta | [2, 931, 2309, 1036, 4]
```
<https://chess.aronpetkovski.com/test/8669/>

LTC SPSA Tune (9375 iterations, 75000 games)

---

CMakeLists.txt
src/engine/evaluation/nnue/arch.h

```
Elo   | 4.52 +- 2.88 (95%)
LLR   | 2.22 (-2.25, 2.89) [0.00, 2.50]
Games | N: 13616 W: 3313 L: 3136 D: 7167
Penta | [14, 1511, 3590, 1670, 23]
```
<https://chess.aronpetkovski.com/test/8790/>

Increase L1 size to 1536

---

src/engine/evaluation/nnue/accumulator.h

Elo   | 3.45 +- 2.23 (95%)
SPRT  | 4.0+0.04s Threads=1 Hash=16MB
LLR   | 2.89 (-2.25, 2.89) [0.00, 2.50]
Games | N: 27284 W: 7340 L: 7069 D: 12875
Penta | [237, 2874, 7200, 3043, 288]
https://furybench.com/test/155/

Finny table fused updates

---

src/data_gen/data_gen.cc
src/engine/evaluation/nnue/accumulator.h
src/engine/evaluation/nnue/nnue.cc
src/engine/evaluation/nnue/sparse.h
src/engine/search/history/continuation_entries.h
src/engine/search/history/correction_history.h
src/engine/search/search.cc
src/engine/search/search.h
src/engine/search/time_mgmt.cc
src/engine/search/time_mgmt.h
src/tests/bench_test.cc
src/utils/time.h

```
Elo   | 3.07 +- 3.04 (95%)
LLR   | 2.91 (-2.25, 2.89) [-3.00, 1.00]
Games | N: 12126 W: 3039 L: 2932 D: 6155
Penta | [52, 1196, 3465, 1293, 57]
```
https://furybench.com/test/160/

Massively improve bench speed

---

src/engine/evaluation/nnue/accumulator.h
src/utils/fused.h
src/utils/types.h
third-party/fmt/test/gtest/gmock/gmock.h

```
Elo   | 1.18 +- 2.16 (95%)
SPRT  | 5.0+0.05s Threads=1 Hash=16MB
LLR   | 2.93 (-2.25, 2.89) [-3.00, 1.00]
Games | N: 27150 W: 6785 L: 6693 D: 13672
Penta | [160, 3028, 7104, 3126, 157]
```
https://furybench.com/test/428/
no functional change

Template fused updates

---

CMakeLists.txt

STC
```
Elo   | 2.69 +- 1.90 (95%)
Games | N: 37398 W: 9486 L: 9196 D: 18716
Penta | [200, 4487, 9040, 4767, 205]
```
https://furybench.com/test/444/
LTC
```
Elo   | 4.30 +- 2.46 (95%)
Games | N: 18980 W: 4644 L: 4409 D: 9927
Penta | [30, 2127, 4931, 2382, 20]
```
https://furybench.com/test/446/

Switch to Zekrom v3 network

---

CMakeLists.txt

STC
```
Elo   | -0.94 +- 2.74 (95%)
LLR   | -1.07 (-2.25, 2.89) [0.00, 2.50]
Games | N: 16968 W: 4141 L: 4187 D: 8640
Penta | [77, 2059, 4238, 2053, 57]
```
https://furybench.com/test/720/
LTC
```
Elo   | 4.93 +- 2.64 (95%)
Games | N: 15780 W: 3796 L: 3572 D: 8412
Penta | [13, 1712, 4216, 1936, 13]
```
https://furybench.com/test/724/

Switch to Zekrom v4 network

---

CMakeLists.txt

STC
```
Elo   | 5.63 +- 2.94 (95%)
LLR   | 2.91 (-2.25, 2.89) [0.00, 2.50]
Games | N: 14876 W: 3741 L: 3500 D: 7635
Penta | [58, 1684, 3738, 1875, 83]
```
https://furybench.com/test/871/
LTC but with rounded input layer
```
Elo   | 6.18 +- 3.03 (95%)
LLR   | 2.91 (-2.25, 2.89) [0.00, 2.50]
Games | N: 12700 W: 3174 L: 2948 D: 6578
Penta | [26, 1386, 3296, 1620, 22]
```
https://furybench.com/test/875/

Switch to Zekrom v5 network

---

Makefile
src/engine/evaluation/evaluation.cc
src/engine/evaluation/evaluation.h
src/engine/search/constants.h
src/engine/search/history/bonus.h
src/engine/search/history/correction_history.h
src/engine/search/history/history.h
src/engine/search/history/pawn_history.h
src/engine/search/move_picker.cc
src/engine/search/search.cc
src/engine/search/time_mgmt.cc
src/tuner/spsa.h

```
Elo   | 6.98 +- 3.21 (95%)
SPRT  | 60.0+0.60s Threads=1 Hash=64MB
Games | N: 10700 W: 2590 L: 2375 D: 5735
Penta | [4, 1145, 2840, 1354, 7]
```
https://furybench.com/test/1121/

LTC SPSA (98k games, 12k iterations)

---

CMakeLists.txt

Fixed Nodes
```
Elo   | 23.55 +- 7.10 (95%)
SPRT  | N=25000 Threads=1 Hash=16MB
Games | N: 4152 W: 1425 L: 1144 D: 1583
Penta | [81, 405, 896, 540, 154]
```
https://furybench.com/test/1479/
STC
```
Elo   | 19.91 +- 5.78 (95%)
LLR   | 2.91 (-2.25, 2.89) [0.00, 2.50]
Games | N: 3896 W: 1143 L: 920 D: 1833
Penta | [11, 381, 959, 568, 29]
```
https://furybench.com/test/1481/
LTC
```
Elo   | 25.88 +- 8.14 (95%)
LLR   | 2.90 (-2.25, 2.89) [0.00, 4.00]
Games | N: 1802 W: 530 L: 396 D: 876
Penta | [1, 160, 452, 280, 8]
```
https://furybench.com/test/1482/

Switch to Zekrom v7 network

---

src/engine/search/search.cc
src/engine/search/search.h

```
Elo   | -1.48 +- 11.58 (95%)
Conf  | 5.0+0.05s Threads=2 Hash=16MB
Games | N: 936 W: 225 L: 229 D: 482
Penta | [3, 115, 237, 109, 4]
```
https://furybench.com/test/1981/
Good enough!

NUMA First Touch Policy for `Thread` objects

---

src/engine/evaluation/evaluation.cc
src/engine/evaluation/evaluation.h
src/engine/search/constants.h
src/engine/search/history/bonus.h
src/engine/search/history/correction_history.h
src/engine/search/history/history.h
src/engine/search/history/pawn_history.h
src/engine/search/move_picker.cc

```
Elo   | 2.48 +- 1.97 (95%)
SPRT  | 60.0+0.60s Threads=1 Hash=64MB
LLR   | 2.91 (-2.25, 2.89) [0.00, 4.00]
Games | N: 27972 W: 6802 L: 6602 D: 14568
Penta | [11, 3119, 7527, 3317, 12]
```
https://furybench.com/test/2012/

LTC SPSA (100k games, 12.5k iterations)
